---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Basantk8/learnk8/tree/main/kubernetes/deployments

